### ISSUE TITLE
Problème de formatage avec {rpg_fields_left.F_NAME} et {rpg_fields.F_NAME}

### ISSUE THREAD

**Issue by PanzerKadaver** [Etana/template#4]
Salutations,

Pour mon forum je travail sur une version custom de la fiche de personnage (à base de CSS maison et javascript).

Seulement je rencontre un problème quand je souhaite utiliser `{rpg_fields_left.F_NAME}` et `{rpg_fields.F_NAME}`

En effet, `{rpg_fields_left.F_NAME}` et `{rpg_fields.F_NAME}`, insèrent le code suivant :

`&nbsp;<span class="gen">F_NAME</span>`

Ce qui, tu en conviendra, n'est pas très pratique quand on veut modifier le template comme suit :

```
<!-- BEGIN rpg_fields_left -->
    <dl>
        <dt class='{rpg_fields_left.F_NAME}'><label>{rpg_fields_left.F_NAME} :</label></dt>
        <dd>{rpg_fields_left.F_VALUE_NEW}</dd>
    </dl>
<!-- END rpg_fields_left -->
```

[...]

```
<!-- BEGIN rpg_fields -->
    <dl>
        <dt class='{rpg_fields.F_NAME}'><label>{rpg_fields.F_NAME} :</label></dt>
        <dd>{rpg_fields.F_VALUE_NEW}</dd>
    </dl>
<!-- END rpg_fields -->
```

Peut-on envisager une modification ou mieux, une valeur alternative du genre :
`{rpg_fields.F_RAW_NAME}` Qui ne contiendrait que le nom du champs en "brut" (minuscule, underscore, pas de code html superflus)

Amicalement,
Marc

**Comment by Etana** [comment]
salut,


seul un devactif saurait le dire, mais vu ça serait utile à fort peu j'imagine que non.

on pourrait mettre `class="f_name"` et ajouter aux pages en question un javascript de ce style :

```js
$(function(){
  $('.f_name').each(function(){ $(this).addClass('fn_'+$(this).text().replace(/[^a-z0-9]/gi, '')) });
});
```

ensuite on peut utiliser `.fn_Rponse42` comme sélecteur pour un champ de nom `Réponse à 42`.

_ps : la section d'entraide et support de forumactif est disponible [ici](http://forum.forumactif.com/c5-entraide-support)._

**Comment by Toxicat** [comment]
Ah bien vu le coup des regexp ! Sur le moment je n'y avais pas pensé.

Pour le coup d'un devactif, je pensais que tu en était un ^^ Le fait d'avoir un github est trompeur.
Pour transmettre ma demande à un devactif, c'est par où ?

**Comment by Etana** [comment]
Si c'était un bug, il y aurait les sections de support et ça pourrait être déplacé si avéré dans besoin d'un dévactif.

Ici ce serait plutôt en ouvrant une suggestion dans la [section de suggestion](http://forum.forumactif.com/f3-vos-suggestions-pour-vos-forums-sondage).

Un dévactif, c'est un développeur employé par la société derrière forumactif. Ce sont les dévactifs qui développent les nouvelles fonctionnalités, résolvent les bugs, améliorent le code, ...

Moi je ne suis qu'un membre bénévole du staff du [forum de support francophone](http://forum.forumactif.com/forum).
